# 将来的には対応する規約の読込
inherit_from: .rubocop_todo.yml

# 追加した規約ファイル読込
require:
  - rubocop-rails

AllCops:
  # Rubyバージョン指定
  TargetRubyVarsion: 2.7.1
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'

# ブロック行数の制限を除外
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

# 文字リテラルのイミュータブル宣言を無視（freezeになるのはRuby3以降）
Style/FrozenStringLiteralComment:
  Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# Gemfileのグループ内Gemのアルファベット順ソートを無視
Bundler/OrderedGems:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# クラスのコメント必須を無視
Style/Documentation:
  Enabled: false

# `Rails.root.join`句を使用するファイルパス結合プロセスの使用法を無視
Rails/FilePath:
  Enabled: false

# 'only'や'except'オプションで指定されたメソッドのクラス内での定義を必須としない
Rails/LexicallyScopedActionFilter:
  Enabled: false
